# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# Test if this works

name: Packaging check Maven

on: pull_request


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Install HiGHS
        run: |
          curl -sL https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases/download/HiGHSstatic-v1.10.0%2B0/HiGHSstatic.v1.10.0.x86_64-linux-gnu-cxx03.tar.gz -o highs.tar.gz
          mkdir /opt/HiGHS
          tar -xf highs.tar.gz -C /opt/HiGHS
          rm highs.tar.gz
          mkdir -p $HOME/bin
          ln -s /opt/HiGHS/bin/highs $HOME/bin/highs
          echo "$HOME/bin" >> $GITHUB_PATH
      - name: Build with Maven
        run: mvn -B package --file pom.xml